# Generated by Django 4.2.11 on 2025-01-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eno',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
